version: '3'

services:
  nexchat:
    image: nexchat:latest-slim
    build:
      context: .
      dockerfile: docker/Dockerfile-slim
    volumes:
      - ./har_and_cookies:/app/har_and_cookies
      - ./generated_images:/app/generated_images
    ports:
      - '8080:1337'
    command: ["python", "-m", "g4f"]