version: '3.8'

services:
  nexchat:
    build: .
    container_name: nexchat
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - nexchat_data:/app/data

volumes:
  nexchat_data:
    driver: local
